### ISSUE TITLE
Acceso a Khenshin Pod

### ISSUE THREAD

**Issue by christiams** [khipu/khipu-inside-demo#2]
Para compilar para iOS se necesita acceso al pod https://bitbucket.org/khipu/khenshin-pod.git pero está privado =(

Y para compilar para Android se necesita acceso al Maven https://dev.khipu.com/nexus/content/repositories/browser2app y tambien pide clave =(

**Comment by edavism** [comment]
Hola, hemos creado un repositorio público para los cocoa pods y para los aar de khenshin.

Los nuevos repositorios son:
https://github.com/khipu/khenshin-pod y https://dev.khipu.com/nexus/content/repositories/khenshin/ respectivamente
